/** Seed patients for first launch. Subsequent edits live in localStorage. */
window.JR_SEED_PATIENTS = [
  {
    id: "pt-vasquez",
    firstName: "Elena",
    middleName: "M",
    lastName: "Vasquez",
    dob: "1958-03-14",
    sex: "F",
    phone: "(602) 555-0148",
    email: "e.vasquez@email.example",
    address: "418 S Maple Ave",
    city: "Mesa",
    state: "AZ",
    zip: "85210",
    mrn: "JR-10482",
    emergencyName: "Luis Vasquez",
    emergencyPhone: "(602) 555-0149",
    insuranceType: "Medicare Advantage",
    payerName: "Humana",
    memberId: "H9984-220183",
    groupNumber: "AZ-MA-441",
    relationship: "self",
    subscriberName: "",
    subscriberDob: "",
    subscriberSex: "",
    subscriberAddress: "",
    anotherPlan: false,
    secondaryPayer: "",
    secondaryMemberId: "",
    secondaryGroup: "",
    employmentRelated: false,
    autoAccident: false,
    otherAccident: false,
    signatureOnFile: true,
    inbound: {
      name: "Rachel Cho, MD",
      npi: "1871654321",
      date: "2024-11-02",
      specialty: "Internal Medicine",
      practice: "Desert Primary Care",
      phone: "(480) 555-0110",
      info: "Transferred for ongoing diabetes and hypertension management. Palpitations noted at last PCP visit; please evaluate and assume specialty follow-up as needed.",
    },
    medications: [
      {
        id: "med-1",
        name: "Atorvastatin",
        strength: "40 mg",
        directions: "1 tab PO nightly",
        action: "change",
      },
      {
        id: "med-2",
        name: "Metformin ER",
        strength: "1000 mg",
        directions: "1 tab PO BID with meals",
        action: "continue",
      },
      {
        id: "med-3",
        name: "Lisinopril",
        strength: "20 mg",
        directions: "1 tab PO daily",
        action: "continue",
      },
      {
        id: "med-4",
        name: "Amlodipine",
        strength: "5 mg",
        directions: "1 tab PO daily",
        action: "continue",
      },
    ],
    medicationHistory: [
      {
        id: "hist-1",
        name: "Simvastatin",
        strength: "20 mg",
        directions: "1 tab PO nightly",
        stoppedAt: "2026-02-12",
        stopReason: "Switched to atorvastatin 40 mg for stronger LDL reduction.",
        physicianApproved: true,
      },
      {
        id: "hist-2",
        name: "Hydrochlorothiazide",
        strength: "25 mg",
        directions: "1 tab PO daily",
        stoppedAt: "2025-11-03",
        stopReason: "Ankle swelling; blood pressure controlled on lisinopril + amlodipine.",
        physicianApproved: true,
      },
    ],
    referralHistory: [
      {
        id: "refh-1",
        specialty: "Endocrinology",
        toProvider: "Sunrise Endocrine",
        reason: "Outside diabetes co-management.",
        date: "2026-01-15",
        status: "scheduled",
        authNumber: "HUM-1102",
        stoppedAt: "2026-04-02",
        stopReason: "Care assumed in this office; outside endocrine follow-up no longer needed.",
        physicianApproved: true,
      },
    ],
    outbound: [
      {
        id: "ref-1",
        specialty: "Cardiology",
        toProvider: "Anita Patel, MD",
        reason: "New atrial fibrillation workup; consider anticoagulation.",
        date: "2026-08-08",
        status: "pending",
        authNumber: "",
      },
      {
        id: "ref-2",
        specialty: "Ophthalmology",
        toProvider: "Desert Eye Associates",
        reason: "Annual diabetic retinal screening.",
        date: "2026-07-22",
        status: "scheduled",
        authNumber: "AUTH-882194",
      },
    ],
    diagnoses: [
      { code: "E11.9", label: "Type 2 diabetes mellitus without complications" },
      { code: "I10", label: "Essential (primary) hypertension" },
      { code: "E78.5", label: "Hyperlipidemia, unspecified" },
      { code: "I48.91", label: "Unspecified atrial fibrillation" },
    ],
    notes:
      "67F with T2DM, HTN, HLD. Reports palpitations × 2 weeks. A1c 7.4 last month. Statin changed from simvastatin to atorvastatin. RTC 4 weeks or sooner if syncope.",
    noteHistory: [
      {
        date: "2026-07-02",
        text: "Diabetes follow-up. A1c 7.4. Home sugars 120–160. Continue metformin ER. Discussed statin intensity; remain on simvastatin pending labs. BP 138/82.",
      },
      {
        date: "2026-03-18",
        text: "BP still above goal on lisinopril 20 mg. Added amlodipine 5 mg daily. No edema. Recheck in 4 weeks. Fasting lipids ordered.",
      },
      {
        date: "2025-11-12",
        text: "Ankle swelling on HCTZ. Stopped HCTZ; continue lisinopril. Weight stable. RTC 3 months or sooner if swelling persists.",
      },
    ],
  },
  {
    id: "pt-okonkwo",
    firstName: "James",
    middleName: "",
    lastName: "Okonkwo",
    dob: "1971-11-02",
    sex: "M",
    phone: "(480) 555-0192",
    email: "j.okonkwo@email.example",
    address: "90 W Encanto Blvd",
    city: "Phoenix",
    state: "AZ",
    zip: "85003",
    mrn: "JR-09817",
    emergencyName: "Amaka Okonkwo",
    emergencyPhone: "(480) 555-0193",
    insuranceType: "Group",
    payerName: "Aetna",
    memberId: "W251889344",
    groupNumber: "G-88421",
    relationship: "self",
    subscriberName: "",
    subscriberDob: "",
    subscriberSex: "",
    subscriberAddress: "",
    anotherPlan: false,
    secondaryPayer: "",
    secondaryMemberId: "",
    secondaryGroup: "",
    employmentRelated: false,
    autoAccident: false,
    otherAccident: false,
    signatureOnFile: true,
    inbound: {
      name: "",
      npi: "",
      date: "",
      specialty: "",
      practice: "",
      phone: "",
      info: "",
    },
    medications: [
      {
        id: "med-5",
        name: "Adalimumab",
        strength: "40 mg",
        directions: "SQ every 14 days",
        action: "continue",
      },
      {
        id: "med-6",
        name: "Methotrexate",
        strength: "15 mg",
        directions: "PO weekly (Thursday)",
        action: "continue",
      },
      {
        id: "med-7",
        name: "Folic acid",
        strength: "1 mg",
        directions: "1 tab PO daily except Thursday",
        action: "continue",
      },
    ],
    medicationHistory: [
      {
        id: "hist-3",
        name: "Prednisone",
        strength: "10 mg",
        directions: "Taper as directed",
        stoppedAt: "2026-06-18",
        stopReason: "Flare taper completed; resumed baseline MTX + adalimumab.",
        physicianApproved: true,
      },
    ],
    referralHistory: [
      {
        id: "refh-2",
        specialty: "OT / PT",
        toProvider: "Desert Hand Therapy",
        reason: "Hand stiffness and grip limitation during RA flare.",
        date: "2026-03-04",
        status: "scheduled",
        authNumber: "AET-338011",
        stoppedAt: "2026-06-20",
        stopReason: "Course completed; function improved after flare controlled.",
        physicianApproved: true,
      },
    ],
    outbound: [
      {
        id: "ref-3",
        specialty: "Rheumatology",
        toProvider: "Valley Arthritis Center — Dr. Kim",
        reason: "Ongoing RA management; adalimumab renewal documentation.",
        date: "2026-08-01",
        status: "authorized",
        authNumber: "AET-441902",
      },
    ],
    diagnoses: [{ code: "M06.9", label: "Rheumatoid arthritis, unspecified" }],
    notes:
      "Stable on MTX + adalimumab. Morning stiffness ~20 min. No injection-site reactions. Labs (CBC, CMP, LFTs) drawn today. Patient traveling in September — refill 90-day supply.",
    noteHistory: [
      {
        date: "2026-05-14",
        text: "RA moderately active. Morning stiffness 45 min. Increased methotrexate to 15 mg weekly. Continue adalimumab. TB screen negative. Folate counseling reviewed.",
      },
      {
        date: "2026-02-20",
        text: "Started adalimumab 40 mg SQ every 14 days after incomplete response to MTX alone. Injection teaching completed. Follow up in 12 weeks.",
      },
    ],
  },
  {
    id: "pt-shah",
    firstName: "Priya",
    middleName: "R",
    lastName: "Shah",
    dob: "1994-06-21",
    sex: "F",
    phone: "(623) 555-0166",
    email: "priya.shah@email.example",
    address: "12 N 3rd St Apt 4B",
    city: "Phoenix",
    state: "AZ",
    zip: "85004",
    mrn: "JR-12105",
    emergencyName: "Asha Shah",
    emergencyPhone: "(623) 555-0167",
    insuranceType: "HMO",
    payerName: "Blue Shield",
    memberId: "XBS-3301987",
    groupNumber: "EMP-219",
    relationship: "self",
    subscriberName: "",
    subscriberDob: "",
    subscriberSex: "",
    subscriberAddress: "",
    anotherPlan: false,
    secondaryPayer: "",
    secondaryMemberId: "",
    secondaryGroup: "",
    employmentRelated: false,
    autoAccident: false,
    otherAccident: false,
    signatureOnFile: true,
    inbound: {
      name: "Self-referred",
      npi: "",
      date: "2026-08-12",
      specialty: "",
      practice: "",
      phone: "",
      info: "New prenatal patient. No outside referring physician; established care at this practice.",
    },
    medications: [
      {
        id: "med-8",
        name: "Sertraline",
        strength: "50 mg",
        directions: "1 tab PO daily",
        action: "continue",
      },
      {
        id: "med-9",
        name: "Prenatal vitamin",
        strength: "1 tab",
        directions: "1 tab PO daily",
        action: "start",
      },
    ],
    medicationHistory: [
      {
        id: "hist-4",
        name: "Ibuprofen",
        strength: "400 mg",
        directions: "1 tab PO PRN headache",
        stoppedAt: "2026-07-01",
        stopReason: "Stopped after positive pregnancy test; use acetaminophen instead.",
        physicianApproved: true,
      },
    ],
    referralHistory: [
      {
        id: "refh-3",
        specialty: "Psychiatry",
        toProvider: "North Valley Behavioral",
        reason: "Anxiety management prior to conception.",
        date: "2026-04-10",
        status: "authorized",
        authNumber: "HMO-7721",
        stoppedAt: "2026-07-08",
        stopReason: "Stable on sertraline; prenatal care will coordinate further counseling.",
        physicianApproved: true,
      },
    ],
    outbound: [
      {
        id: "ref-4",
        specialty: "Maternal-Fetal Medicine",
        toProvider: "Banner MFM",
        reason: "G1P0, 12w; history of anxiety on SSRI — counseling on continuation.",
        date: "2026-08-12",
        status: "requested",
        authNumber: "",
      },
    ],
    diagnoses: [
      { code: "Z34.90", label: "Encounter for supervision of normal pregnancy, unspecified" },
      { code: "F41.1", label: "Generalized anxiety disorder" },
    ],
    notes:
      "First prenatal visit at this practice. Confirm dating US. Continue sertraline; discussed risks/benefits. HMO — MFM needs plan authorization before scheduling.",
    noteHistory: [
      {
        date: "2026-05-20",
        text: "Preconception visit. Anxiety well controlled on sertraline 50 mg. Discussed continuing SSRI if pregnancy occurs. Started prenatal vitamin. Rubella immune.",
      },
    ],
  },
];

window.JR_PAYERS = [
  "Aetna",
  "Anthem",
  "Blue Cross Blue Shield",
  "Blue Shield",
  "Cigna",
  "Humana",
  "Kaiser Permanente",
  "Medicaid",
  "Medicare",
  "Tricare",
  "UnitedHealthcare",
  "Other",
];

window.JR_INSURANCE_TYPES = [
  "Medicare",
  "Medicare Advantage",
  "Medicaid",
  "Tricare",
  "CHAMPVA",
  "Group",
  "PPO",
  "HMO",
  "EPO",
  "HDHP",
  "Other",
];

window.JR_SPECIALTIES = [
  "Cardiology",
  "Dermatology",
  "Endocrinology",
  "Gastroenterology",
  "Maternal-Fetal Medicine",
  "Nephrology",
  "Neurology",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "OT / PT",
  "Pain Management",
  "Psychiatry",
  "Pulmonology",
  "Rheumatology",
  "Surgery",
  "Urology",
  "Other",
];

window.JR_ICD10 = [
  { code: "E11.9", label: "Type 2 diabetes mellitus without complications" },
  { code: "E11.65", label: "Type 2 diabetes mellitus with hyperglycemia" },
  { code: "E78.5", label: "Hyperlipidemia, unspecified" },
  { code: "E78.2", label: "Mixed hyperlipidemia" },
  { code: "I10", label: "Essential (primary) hypertension" },
  { code: "I11.9", label: "Hypertensive heart disease without heart failure" },
  { code: "I25.10", label: "Atherosclerotic heart disease of native coronary artery" },
  { code: "I48.91", label: "Unspecified atrial fibrillation" },
  { code: "I50.9", label: "Heart failure, unspecified" },
  { code: "J44.9", label: "COPD, unspecified" },
  { code: "J45.909", label: "Unspecified asthma, uncomplicated" },
  { code: "N18.3", label: "Chronic kidney disease, stage 3" },
  { code: "M06.9", label: "Rheumatoid arthritis, unspecified" },
  { code: "M17.11", label: "Unilateral primary osteoarthritis, right knee" },
  { code: "M54.5", label: "Low back pain" },
  { code: "G43.909", label: "Migraine, unspecified, not intractable" },
  { code: "F32.9", label: "Major depressive disorder, single episode, unspecified" },
  { code: "F41.1", label: "Generalized anxiety disorder" },
  { code: "F41.9", label: "Anxiety disorder, unspecified" },
  { code: "E66.9", label: "Obesity, unspecified" },
  { code: "E03.9", label: "Hypothyroidism, unspecified" },
  { code: "D64.9", label: "Anemia, unspecified" },
  { code: "K21.9", label: "GERD without esophagitis" },
  { code: "N39.0", label: "Urinary tract infection, site not specified" },
  { code: "J06.9", label: "Acute upper respiratory infection, unspecified" },
  { code: "Z00.00", label: "Encounter for general adult medical examination" },
  { code: "Z23", label: "Encounter for immunization" },
  { code: "Z34.90", label: "Encounter for supervision of normal pregnancy, unspecified" },
  { code: "Z79.4", label: "Long term (current) use of insulin" },
  { code: "Z79.82", label: "Long term (current) use of aspirin" },
  { code: "Z87.891", label: "Personal history of nicotine dependence" },
  { code: "Z99.2", label: "Dependence on renal dialysis" },
];
